version: "3.7"

services:
  database:
    image: postgres
    container_name: database_app
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_app
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app-teste-devires
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local